"""empty message

Revision ID: a4c52cb8dd70
Revises: 046e3016d433
Create Date: 2024-09-18 23:16:00.603729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4c52cb8dd70'
down_revision: Union[str, None] = '046e3016d433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('questions', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subject', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('questions', 'title')
    # ### end Alembic commands ###
